version: "2"
services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - /home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker # check if which docler is /usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose # to run docker-compose
